version: "3.8"
services:
    mongodb:
        image: mongo:5.0
        container_name: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
        volumes:
            - /database:/data/db
        ports:
            - 27017:27017
